package application

import (
	"context"
	"fmt"
	"github.com/matiasbinagora/inventory-dashboard/internal/domain"
)

type Repository interface {
	CreateProject(context.Context, domain.Project) (domain.Project, error)
	ListProjects(context.Context) ([]domain.Project, error)
	GetProject(context.Context, string) (domain.Project, error)
	UpdateProject(context.Context, domain.Project) error
	DeleteProject(context.Context, string) error
	AddLink(context.Context, domain.PublicLink) (domain.PublicLink, error)
	DeleteLink(context.Context, string, string) error
	AddTechnology(context.Context, string, string) error
	AddMedia(context.Context, domain.MediaAsset) (domain.MediaAsset, error)
	DeleteMedia(context.Context, string, string) error
	AddMilestone(context.Context, domain.Milestone) (domain.Milestone, error)
	UpdateMilestone(context.Context, domain.Milestone) error
	DeleteMilestone(context.Context, string, string) error
}

// AtomicProjectCreator is implemented by persistence adapters that can write
// a project aggregate in one transaction. Repository remains unchanged so
// existing adapters and test doubles keep their current contract.
type AtomicProjectCreator interface {
	CreateProjectWithChildren(context.Context, domain.Project) (domain.Project, error)
}

type Inventory struct{ repository Repository }

func NewInventory(repository Repository) *Inventory { return &Inventory{repository: repository} }

func (i *Inventory) CreateProject(ctx context.Context, project domain.Project) (domain.Project, error) {
	if err := validateProjectChildren(project); err != nil {
		return domain.Project{}, err
	}
	if creator, ok := i.repository.(AtomicProjectCreator); ok {
		return creator.CreateProjectWithChildren(ctx, project)
	}
	created, err := i.repository.CreateProject(ctx, domain.Project{Name: project.Name, Description: project.Description, AgenticPlatform: project.AgenticPlatform, Technologies: project.Technologies})
	if err != nil {
		return domain.Project{}, err
	}
	for _, link := range project.Links {
		link.ProjectID = created.ID
		if _, err := i.repository.AddLink(ctx, link); err != nil {
			return domain.Project{}, err
		}
	}
	for _, media := range project.Media {
		media.ProjectID = created.ID
		if _, err := i.repository.AddMedia(ctx, media); err != nil {
			return domain.Project{}, err
		}
	}
	for _, milestone := range project.Milestones {
		milestone.ProjectID = created.ID
		if _, err := i.repository.AddMilestone(ctx, milestone); err != nil {
			return domain.Project{}, err
		}
	}
	return i.repository.GetProject(ctx, created.ID)
}

func validateProjectChildren(project domain.Project) error {
	if err := project.Validate(); err != nil {
		return err
	}
	for _, link := range project.Links {
		if link.ID != "" || link.ProjectID != "" {
			return fmt.Errorf("%w: child identifiers are generated by the application", domain.ErrInvalidProject)
		}
		if err := link.Validate(); err != nil {
			return err
		}
	}
	for _, media := range project.Media {
		if media.ID != "" || media.ProjectID != "" {
			return fmt.Errorf("%w: child identifiers are generated by the application", domain.ErrInvalidProject)
		}
		if err := media.Validate(); err != nil {
			return err
		}
	}
	for _, milestone := range project.Milestones {
		if milestone.ID != "" || milestone.ProjectID != "" {
			return fmt.Errorf("%w: child identifiers are generated by the application", domain.ErrInvalidProject)
		}
		if err := milestone.Validate(); err != nil {
			return err
		}
	}
	return nil
}

func (i *Inventory) ListProjects(ctx context.Context) ([]domain.Project, error) {
	return i.repository.ListProjects(ctx)
}
func (i *Inventory) GetProject(ctx context.Context, id string) (domain.Project, error) {
	return i.repository.GetProject(ctx, id)
}
func (i *Inventory) UpdateProject(ctx context.Context, project domain.Project) error {
	return i.repository.UpdateProject(ctx, project)
}
func (i *Inventory) DeleteProject(ctx context.Context, id string) error {
	return i.repository.DeleteProject(ctx, id)
}

func (i *Inventory) AddLink(ctx context.Context, link domain.PublicLink) (domain.PublicLink, error) {
	if err := link.Validate(); err != nil {
		return domain.PublicLink{}, err
	}
	return i.repository.AddLink(ctx, link)
}
func (i *Inventory) DeleteLink(ctx context.Context, projectID, id string) error {
	return i.repository.DeleteLink(ctx, projectID, id)
}
func (i *Inventory) AddTechnology(ctx context.Context, projectID, technology string) error {
	return i.repository.AddTechnology(ctx, projectID, technology)
}
func (i *Inventory) AddMedia(ctx context.Context, media domain.MediaAsset) (domain.MediaAsset, error) {
	if err := media.Validate(); err != nil {
		return domain.MediaAsset{}, err
	}
	return i.repository.AddMedia(ctx, media)
}
func (i *Inventory) DeleteMedia(ctx context.Context, projectID, id string) error {
	return i.repository.DeleteMedia(ctx, projectID, id)
}
func (i *Inventory) AddMilestone(ctx context.Context, milestone domain.Milestone) (domain.Milestone, error) {
	if err := milestone.Validate(); err != nil {
		return domain.Milestone{}, err
	}
	return i.repository.AddMilestone(ctx, milestone)
}
func (i *Inventory) UpdateMilestone(ctx context.Context, milestone domain.Milestone) error {
	return i.repository.UpdateMilestone(ctx, milestone)
}
func (i *Inventory) DeleteMilestone(ctx context.Context, projectID, id string) error {
	return i.repository.DeleteMilestone(ctx, projectID, id)
}
